name: stonkleton_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - requests
  - ipython
  - pandas
  - pyinstaller
  - prettytable
  - python-telegram-bot
  - python-dotenv
  - pip
  - pip:
    - yahooquery
